spring:
  application:
    name: weka
---
gemini:
  api:
    key: AIzaSyAqanV4W842L0xFOJHo6YazO0MTUBGhLPE
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=